export interface AppItem {
  id: string;
  path: string;
  title: string;
  subtitle: string;
  description: string;
  iconURL: string;
  heroURL: string;
  linkURL: string;
  categories?: string[]; // e.g., ['Productivity', 'AI']
  tags?: string[]; // e.g., ['notes', 'organizer', 'task manager']
}

export const apps: AppItem[] = [
  {
    id: "ActivityBuilder",
    path: "ActivityBuilder",
    title: "ActivityBuilder",
    subtitle: "Customise your Lock Screen",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.ActivityBuilder/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6443593416",
    categories: [],
    tags: [],
  },
  {
    id: "MusicView",
    path: "MusicView",
    title: "MusicView",
    subtitle: "Spotify and Music Widget",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.MusicView/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1531442783",
    categories: [],
    tags: [],
  },
  {
    id: "MusicViewPro",
    path: "MusicViewPro",
    title: "MusicView Pro",
    subtitle: "Interactive Music Widgets",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.MusicView-Pro/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6450147372",
    categories: [],
    tags: [],
  },
  {
    id: "ControlBar",
    path: "ControlBar",
    title: "ControlBar",
    subtitle: "Music Widget Control & Actions",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.ControlBar/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6459730205",
    categories: [],
    tags: [],
  },
  {
    id: "FloatingPlayer",
    path: "FloatingPlayer",
    title: "FloatingPlayer",
    subtitle: "Picture in Picture for Music",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.FloatingPlayer/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1601556396",
    categories: [],
    tags: [],
  },
  {
    id: "SocialStats",
    path: "SocialStats",
    title: "Social Stats Widget",
    subtitle: "Social Media Profile Widgets",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.FollowersWidget/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1533776006",
    categories: [],
    tags: [],
  },
  {
    id: "SongSwipe",
    path: "SongSwipe",
    title: "SongSwipe",
    subtitle: "Discover music, make playlists",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.SongSwipe/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1625641475",
    categories: [],
    tags: [],
  },
  {
    id: "LockLauncher",
    path: "LockLauncher",
    title: "LockLauncher",
    subtitle: "Lock Screen Widgets & Launcher",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.LockLauncher/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1631920238",
    categories: [],
    tags: [],
  },
  {
    id: "RCReporting",
    path: "RCReporting",
    title: "RCReporting",
    subtitle: "RevenueCat Client & Dashboard",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.rcreporting/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1511127976",
    categories: [],
    tags: [],
  },
  {
    id: "TodayTab",
    path: "TodayTab",
    title: "TodayTab",
    subtitle: "Customise your Safari Start Page",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.TodayTab/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1588593096",
    categories: [],
    tags: [],
  },
  {
    id: "SongList",
    path: "SongList",
    title: "SongList",
    subtitle: "Listen Later - Songs & Albums",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.SongList/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1614122341",
    categories: [],
    tags: [],
  },
  {
    id: "Applytics",
    path: "Applytics",
    title: "Applytics",
    subtitle: "App Sales & Metrics Reporting",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.applytics/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1584323787",
    categories: [],
    tags: [],
  },
  {
    id: "ContactsBot",
    path: "ContactsBot",
    title: "ContactsBot",
    subtitle: "The powerful contacts app",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.ContactsBot/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1575124462",
    categories: [],
    tags: [],
  },
  {
    id: "PriceManager",
    path: "PriceManager",
    title: "PriceManager",
    subtitle: "Plan & Change your App Prices",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.pricemanager/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1564231812",
    categories: [],
    tags: [],
  },
  {
    id: "SecurityKit",
    path: "SecurityKit",
    title: "SecurityKit",
    subtitle: "Security tools for developers",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.SecurityKit/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1548808907",
    categories: [],
    tags: [],
  },
  {
    id: "ReviewKit",
    path: "ReviewKit",
    title: "ReviewKit",
    subtitle: "Track ratings and reviews",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.ReviewKit/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1546576718",
    categories: [],
    tags: [],
  },
  {
    id: "StrengthBot",
    path: "StrengthBot",
    title: "StrengthBot",
    subtitle: "Gym Strength Tracker & Manager",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.StrengthBot/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1566114294",
    categories: [],
    tags: [],
  },
  {
    id: "SalesBot",
    path: "SalesBot",
    title: "SalesBot for Appfigures",
    subtitle: "Track sales, ads & downloads",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.SalesBot/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1540447424",
    categories: [],
    tags: [],
  },
  {
    id: "LaunchWidgets",
    path: "LaunchWidgets",
    title: "Launch Widgets",
    subtitle: "Quick widget actions",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.LaunchWidgets/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1540447424",
    categories: [],
    tags: [],
  },
  {
    id: "CryptoDNS",
    path: "CryptoDNS",
    title: "CryptoDNS",
    subtitle: "Stay safe and secure online",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.CryptoDNS/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1520888363",
    categories: [],
    tags: [],
  },
  {
    id: "WallWidgets",
    path: "WallWidgets",
    title: "- (Dash) Transparent",
    subtitle: "Transparent widgets & overlays",
    description: "",
    iconURL:
      "https://is2-ssl.mzstatic.com/image/thumb/Purple124/v4/5a/ee/ea/5aeeeaba-1e23-2548-3c6c-d7e61d30787e/AppIcon-1x_U007emarketing-0-10-0-85-220.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1537880763",
    categories: [],
    tags: [],
  },
  {
    id: "SimpleWidgets",
    path: "SimpleWidgets",
    title: "SimpleWidgets",
    subtitle: "Customise your home screen",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.SimpleWidgets/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1537880763",
    categories: [],
    tags: [],
  },
  {
    id: "ColorBox",
    path: "ColorBox",
    title: "Color Box",
    subtitle: "A simple fun game",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.ColorBox/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1471935296",
    categories: [],
    tags: [],
  },
  {
    id: "RaindropWeather",
    path: "RaindropWeather",
    title: "Raindrop Weather",
    subtitle: "A simple weather app",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.RaindropWeather/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1445374719",
    categories: [],
    tags: [],
  },
  {
    id: "AddOne",
    path: "AddOne",
    title: "Add One",
    subtitle: "Challenge your concentration",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/1a/76/fc/1a76fce2-5572-cf63-0d95-9d5e6076a1bd/AppIcon-0-1x_U007emarketing-0-0-85-220-0-7.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1441608877",
    categories: [],
    tags: [],
  },
  {
    id: "ColorJump",
    path: "ColorJump",
    title: "Color Jump!",
    subtitle: "Simple and Addictive!",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/e0/2c/62/e02c6232-c94d-4d3c-3736-a5e9c9bc7a43/AppIcon-1x_U007emarketing-85-220-0-5.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1335515793",
    categories: [],
    tags: [],
  },
  {
    id: "WebInspect",
    path: "WebInspect",
    title: "Web Inspect",
    subtitle: "Great tool for web developers",
    description: "",
    iconURL:
      "https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/62/5f/be/625fbeea-8791-c0e0-4113-29850b40dc4e/AppIcon-1x_U007emarketing-85-220-0-5.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1333379507",
    categories: [],
    tags: [],
  },
  {
    id: "ShadowConnect",
    path: "ShadowConnect",
    title: "Shadow Connect",
    subtitle: "A Shadowsocks Client",
    description: "",
    iconURL:
      "https://is5-ssl.mzstatic.com/image/thumb/Purple126/v4/57/14/c9/5714c9d5-c35e-5b55-a1b1-9688c9d3701c/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-7.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1441410830",
    categories: [],
    tags: [],
  },
  {
    id: "NCEAStudy",
    path: "NCEAStudy",
    title: "NCEA Study",
    subtitle: "NCEA Past Papers",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/2c/5f/49/2c5f4956-d833-dc72-47aa-522b23b197f2/AppIcon-0-1x_U007emarketing-0-7-0-85-220.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1439282798",
    categories: [],
    tags: [],
  },
  {
    id: "iSniffer",
    path: "iSniffer",
    title: "iSniffer",
    subtitle: "View Network Requests",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/1f/4d/40/1f4d404d-ca4d-f721-9b32-5809490a697b/AppIcon-0-1x_U007emarketing-0-0-85-220-0-10.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1436431394",
    categories: [],
    tags: [],
  },
  {
    id: "OpenTunnel",
    path: "OpenTunnel",
    title: "OpenTunnel",
    subtitle: "An OpenVPN Client",
    description: "",
    iconURL:
      "https://is4-ssl.mzstatic.com/image/thumb/Purple128/v4/4e/3d/53/4e3d5325-9624-c565-02d8-fe1d2bef00d9/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-10.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1410669066",
    categories: [],
    tags: [],
  },
  {
    id: "iHost",
    path: "iHost",
    title: "iHost - HTML Live",
    subtitle: "An essential for developers",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/ab/92/d1/ab92d17b-4e5b-0c75-7438-fa4b8aea9e91/AppIcon-1x_U007emarketing-85-220-0-9.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1338576676",
    categories: [],
    tags: [],
  },
  {
    id: "StealthShield",
    path: "StealthShield",
    title: "Stealth Shield",
    subtitle: "Unlimited Privacy & Security",
    description: "",
    iconURL:
      "https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/fd/45/84/fd4584ab-07a9-943f-43a8-0db569dc2dfd/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/460x0w.webp",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1358027922",
    categories: [],
    tags: [],
  },
  {
    id: "AdView",
    path: "AdView",
    title: "AdView",
    subtitle: "AdMob & AdSense earnings",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.adview/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id1671710414",
    categories: [],
    tags: [],
  },
  {
    id: "SongView",
    path: "SongView",
    title: "SongView",
    subtitle: "Music Live Activities Widget",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.songview/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6447479401",
    categories: [],
    tags: [],
  },
  {
    id: "IdeaLog",
    path: "IdeaLog",
    title: "IdeaLog",
    subtitle: "Log, organise and manage your ideas",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.IdeaLog/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6447479401",
    categories: [],
    tags: [],
  },
  {
    id: "HealthBot",
    path: "HealthBot",
    title: "HealthBot",
    subtitle: "Smart Food Tracking",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.HealthBot/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6447813867",
    categories: [],
    tags: [],
  },
  {
    id: "AIImage",
    path: "AIImage",
    title: "AI Image",
    subtitle: "AI Image Generator",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Image/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6472991036",
    categories: [],
    tags: [],
  },
  {
    id: "AIPhotoEnhancer",
    path: "AIPhotoEnhancer",
    title: "AI Photo Enhancer",
    subtitle: "Create AI Image Variations",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Image-Enhancer/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6473685152",
    categories: [],
    tags: [],
  },
  {
    id: "AIVoice",
    path: "AIVoice",
    title: "AI Voice",
    subtitle: "Text to Speech with AI",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Voice/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6473822623",
    categories: [],
    tags: [],
  },
  {
    id: "GoalTracker",
    path: "GoalTracker",
    title: "Goal Tracker",
    subtitle: "Track and achieve your goals",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Goal-Tracker/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6474997090",
    categories: [],
    tags: [],
  },
  {
    id: "AIEmail",
    path: "AIEmail",
    title: "AI Email",
    subtitle: "Create emails with AI",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Email/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6476844199",
    categories: [],
    tags: [],
  },
  {
    id: "GrammarCheck",
    path: "GrammarCheck",
    title: "Grammar Check",
    subtitle: "AI Grammar Check",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Grammar-Check/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6477149776",
    categories: [],
    tags: [],
  },
  {
    id: "QuitVaping",
    path: "QuitVaping",
    title: "Quit Vaping",
    subtitle: "Quit Vaping Now!",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Quit-Vaping/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6477567025",
    categories: [],
    tags: [],
  },
  {
    id: "AILogo",
    path: "AILogo",
    title: "AI Logo",
    subtitle: "AI Logo Generator",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Logo/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6477750417",
    categories: [],
    tags: [],
  },
  {
    id: "AIWriter",
    path: "AIWriter",
    title: "AI Writer",
    subtitle: "AI Writing Assistant",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Writer/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6478188140",
    categories: [],
    tags: [],
  },
  {
    id: "VoiceGenerator",
    path: "VoiceGenerator",
    title: "Voice Generator",
    subtitle: "AI Powered Voice Generation",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Voice-Generator/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6478903277",
    categories: [],
    tags: [],
  },
  {
    id: "AIMusic",
    path: "AIMusic",
    title: "AI Music",
    subtitle: "AI Powered Music Generation",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Music/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6480380935",
    categories: [],
    tags: [],
  },
  {
    id: "SongCover",
    path: "SongCover",
    title: "Song Cover",
    subtitle: "AI Generated Song Covers",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Song-Cover/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6502046156",
    categories: [],
    tags: [],
  },
  {
    id: "CashGrid",
    path: "CashGrid",
    title: "Cash Grid",
    subtitle: "A new way to track your savings",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.CashGrid/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6714471349",
    categories: [],
    tags: [],
  },
  {
    id: "AIDesign",
    path: "AIDesign",
    title: "AI Design",
    subtitle: "Your personal AI Designer",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.AI-Design/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6737711207",
    categories: [],
    tags: [],
  },
  {
    id: "DogIdentifier",
    path: "DogIdentifier",
    title: "Dog Identifier",
    subtitle: "Identify dogs in just a tap",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Dog-Identifier/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6739771702",
    categories: [],
    tags: [],
  },
  {
    id: "CatIdentifier",
    path: "CatIdentifier",
    title: "Cat Identifier",
    subtitle: "Identify cats in just a tap",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Cat-Identifier/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6739974423",
    categories: [],
    tags: [],
  },
  {
    id: "InteriorDesign",
    path: "InteriorDesign",
    title: "Interior Design",
    subtitle: "Design your dream home",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Interior-Design/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6741510597",
    categories: [],
    tags: [],
  },
  {
    id: "ToonKit",
    path: "ToonKit",
    title: "Cartoon Image: ToonKit",
    subtitle: "Cartoonify any image",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Cartoon-Image/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6743953933",
    categories: [],
    tags: [],
  },
  {
    id: "VibeShift",
    path: "VibeShift",
    title: "VibeShift",
    subtitle: "Switch up your vibe",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.VibeShift/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6746059887",
    categories: [],
    tags: [],
  },
  {
    id: "VidSum",
    path: "VidSum",
    title: "VidSum",
    subtitle: "Summarize Videos",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.VidSum/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6746120652",
    categories: [],
    tags: [],
  },
  {
    id: "JustBookIt",
    path: "JustBookIt",
    title: "JustBookIt",
    subtitle: "Plan your dream holiday in seconds",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.JustBookIt/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6744641144",
    categories: [],
    tags: [],
  },
  {
    id: "Optrix",
    path: "Optrix",
    title: "Optrix",
    subtitle: "Professional headshots in seconds",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Optrix/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6746662820",
    categories: [],
    tags: [],
  },
  {
    id: "CampaignManager",
    path: "CampaignManager",
    title: "Campaign Manager",
    subtitle: "Manage your App Ad Campaigns",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.CampaignManager/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6749494534",
    categories: [],
    tags: [],
  },
  {
    id: "beardfilter",
    path: "BeardFilter",
    title: "Beard Filter",
    subtitle: "Customize your look",
    description: "",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Beard-Filter/large",
    heroURL: "",
    linkURL: "https://apps.apple.com/app/id6749884844",
    categories: [],
    tags: [],
  },
  {
    id: "unblur",
    path: "Unblur",
    title: "Unblur",
    subtitle: "Unblur, restore and improve images",
    description:
      "Unblur - Enhance and Sharpen Your Photos with AI Unblur is an advanced AI-powered photo enhancement app designed to bring clarity and detail back to your blurry images. Whether it's a cherished memory or a professional shot, Unblur helps you restore and enhance your photos effortlessly.",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Unblur/large",
    heroURL:
      "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/93/dc/a4/93dca410-d159-3de9-f23f-a822f97eeb46/Frame_1.png/460x0w.webp",
    linkURL: "https://apps.apple.com/app/id6749494534",
    categories: ["Photography", "AI"],
    tags: ["photos", "images", "AI", "restore", "sharpen", "enhance", "remini"],
  },
  {
    id: "polaroidai",
    path: "PolaroidAI",
    title: "Polaroid AI",
    subtitle:
      "Create polaroid-style images with friends, family or celebrities",
    description:
      "Polaroid AI - Create Custom Polaroids with Anyone Turn memories into timeless keepsakes with Polaroid AI. Whether it's you, your friends, or even your favorite celebrities, bring moments to life in the iconic polaroid style.",
    iconURL:
      "https://www.appatar.io/com.innovativedigitaltechnologies.Polaroid-AI/large",
    heroURL: "/images/featured/polaroid-ai.jpg",
    linkURL: "https://apps.apple.com/app/id6752937087",
    categories: ["Photography", "AI"],
    tags: [
      "photos",
      "images",
      "AI",
      "polaroid",
      "gemini",
      "celebrity",
      "trend",
    ],
  },
];
